### PR TITLE
Add panning using wheel

### PR DESCRIPTION
**Pull request by ajuhos**
This PR adds support for two finger panning on desktop. (#113)
It can be enabled using `pan.wheelEnabled` as it is using the wheel events for panning.

It is a very basic implementation, no velocity, animations, etc., but it works and makes the library more compatible with modern touchpads.

### CODE REVIEW

**Comment by Litterfeldt** [comment]
Need this one as well!

**Comment by devinhalladay** [comment]
@prc5 any chance you could get around to a PR review for this soon?

**Comment by pederjohnsen** [comment]
@ajuhos should there be some override if both `pan` and `wheel` has `wheelEnabled` set to true?
Not sure if there are other options in this lib that contradicts each other, but if both are enabled the experience isn't great so feels like these should only work if the other is disabled 🤔

**Comment by pederjohnsen** [comment]
@ajuhos we're using this in our fork but found that this never triggered `onPanningStart` or `onPanningStop`, for our use case we needed these to trigger for any pan so we updated the code in our fork: https://github.com/thinkproductivity/react-zoom-pan-pinch/commit/c96a8f46453aa18071b3379d7ba95543a9ca63c2

Feel free to add those changes to this PR (all though not sure if this repo is being actively maintained at all 🤔 🤷 )

**Comment by farukparhat** [comment]
Why was this closed? Any chance this is already implemented in the current version?

**Comment by prc5** [comment]
This issue was originally closed because I made major rewrite of basically every module at that time. Currently I'm trying to bring back some of the great ideas so thank you guys!

**Comment by dimensi** [comment]
I invite everyone to my mr, for it is written on the latest version of the https://github.com/BetterTyped/react-zoom-pan-pinch/pull/447 package.

**Comment by edge-rps** [comment]
Solution. #441

**Comment by prc5** [comment]
Great work @dimensi, closing this now as it is completed in v3.4.0! 🚀

**Pull request closed without merging**
