### PR TITLE
feat: add rubberbandIfOutOfBounds

### PR DESCRIPTION
**Pull request by Daydreamer-riri**
Get a better drag effect if out of bounds.

### CODE REVIEW

**Review by prc5 — APPROVED** [review]

**Comment by prc5** [comment]
Looks cool! 🚀

**Comment by Stanzilla** [comment]
This has a regression that no longer lets me drag around my items at all, they all snap back to base

**Comment by Stanzilla** [comment]
@prc5

**Comment by prc5** [comment]
I'm going to check this out

**Pull request merged**
